title: Maria José Jiménez Martín
description: Abogada
site_title: 'Maria José Jiménez Martín - Abogada'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: mariajose
blog_url: https://www.jimenezabogada.com
email: mariajose@jimenezabogada.com
keybase_username: mariajose
twitter_username: mariajose
reddit_username: mariajose

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 